[package]
name = "guessing_game"
version = "0.1.0"
authors = ["joelly <j.ekomalet@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"
rust-string-random = "0.1.0"